strategy:
  matrix:
    windows-1.3:
      image: 'vs2017-win2016'
      standard: 'netstandard1.3'
    windows:
      image: 'vs2017-win2016'
      standard: 'netstandard1.0'
    mac:
      image: 'macos-10.13'
      standard: 'netstandard1.0'
    linux:
      image: 'ubuntu-16.04'
      standard: 'netstandard1.0'

pool:
  vmImage: $(image)

steps:
  - task: DotNetCoreInstaller@0
    displayName: Install
    inputs:
      version: '2.1.505'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/Pfim.csproj'
      arguments: -f $(standard)
  - task: DotNetCoreCLI@2
    displayName: Windows Test
    condition: eq(variables['image'], 'vs2017-win2016')
    inputs:
      command: test
      projects: '**/*Tests.csproj'
      arguments: '-f netcoreapp2.0 --collect "Code coverage"'
  - task: DotNetCoreCLI@2
    displayName: Test
    condition: ne(variables['image'], 'vs2017-win2016')
    inputs:
      command: test
      projects: '**/*Tests.csproj'
      arguments: '-f netcoreapp2.0'
      publishTestResults: false
